version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates monthly
    schedule:
      interval: "daily"
    allow:
      # Allow direct updates only (for packages named in package.json)
      - dependency-type: "direct"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10
    # Add dev team as reviewers
    reviewers:
      - "pressbooks/developers"
